default_language_version:
  python: python3.11

repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/HH-MWB/pyenforce
    rev: v0.1.0
    hooks:
      - id: ruff-format
      - id: ruff-check
      - id: mypy
        additional_dependencies:
          - ".[mypy]"     # Required to re-adds mypy as a dependency
          - pytest
      - id: pylint
        additional_dependencies:
          - ".[pylint]"     # Required to re-adds Pylint as a dependency
          - pytest
      - id: bandit
      - id: semgrep
      - id: vulture

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
