repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy

  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.8
    hooks:
      - id: pylint
        additional_dependencies:
          - pytest

  - repo: https://github.com/pycqa/bandit
    rev: '1.8.6'
    hooks:
      - id: bandit
        args: ['-c', 'pyproject.toml']
