name: Release to PyPI

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: pip install build

      - name: Build package
        run: python -m build

      - name: Release to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Create tag
        run: |
          VERSION=$(python -c "import timerun; print(timerun.__version__)")
          git tag "v$VERSION"
          git push origin "v$VERSION"
